title: 임누리
description: 웹 & 안드로이드앱 개발자
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: NurisPocket
blog_url: https://www.nagekar.com
email: dlasnfl24@gmail.com
keybase_username: dlasnfl24
twitter_username: dlasnfl24@gmail.com
reddit_username: dlasnfl24

# absolute or relative
profile_picture: /assets/images/nuri.jpg

# Google Analytics ID
google_analytics: 