title: NURI LIM
description: Web & Android app Engineer
site_title: '임누리의 포트폴리오에 오신것을 환영합니다'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: NurisPocket
blog_url: 
email: dlasnfl24@gmail.com
keybase_username: dlasnfl24
twitter_username: dlasnfl24@gmail.com
reddit_username: dlasnfl24

# absolute or relative
profile_picture: /assets/images/nuri.jpg

# Google Analytics ID
google_analytics: 